### ISSUE TITLE
Cannot launch the custom component, error at config check

### ISSUE THREAD

**Issue by ursus69** [custom-components/sensor.tautulli#9]
**Version of the custom_component**
latest from Github

**Describe the bug**
After installation of the custom component by the instructions, when doing a `hassio ha check`
the following error appears:

`invalid syntax (tautulli.py, line 9)`

Preceded by the following lines in the log:

`core-ssh:/config# hassio homeassistant check
ERROR
INFO:homeassistant.util.package:Attempting install of colorlog==3.1.4
Testing configuration at /config
ERROR:homeassistant.scripts.check_config:BURB
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/scripts/check_config.py", line 207, in check
    res['components'] = check_ha_config_file(hass)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/scripts/check_config.py", line 372, in check_ha_config_file
    platform = loader.get_platform(hass, domain, p_name)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 60, in get_platform
    return get_component(hass, PLATFORM_FORMAT.format(domain, platform))
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/sensor/tautulli.py", line 9
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Fatal error while loading config: invalid syntax (tautulli.py, line 9)
Failed config
  General Errors: 
    - invalid syntax (tautulli.py, line 9)
Successful config (partial)`

```
Add your logs here.
```

**Comment by ludeeus** [comment]
`<!DOCTYPE html>` You probably did not get the RAW file.
Try this: <https://raw.githubusercontent.com/custom-components/sensor.tautulli/master/custom_components/sensor/tautulli.py>

**Comment by ursus69** [comment]
I am really sorry for having bothered you avec this rookie mistake.
In fact you are right, I did a wget to the file instead of the raw file.
Cordially
